ARG BUILDPLATFORM
FROM --platform=${BUILDPLATFORM:-amd64} alpine AS build

RUN apk add --no-cache \
    nodejs \
    npm {{ options.ship_packages | join(" ") }} {{ options.devel_packages | join(" ") }} && apk cache clean

WORKDIR /home/app

COPY ./ ./
RUN npm i

FROM --platform=${BUILDPLATFORM:-amd64} alpine AS ship
RUN apk add --no-cache \
    nodejs \
    curl {{ options.ship_packages | join " " }}
RUN addgroup -S app && adduser app -S -G app

WORKDIR /home/app
{% for item in options.copy_from_build %}
COPY --from=build /home/app/{{item}}
{% endfor %}
USER app


CMD ["node", "funko.js"]
HEALTHCHECK {{ options.healthcheck_options }}  CMD {{ options.healthcheck_command }}
