ARG BUILDPLATFORM
FROM --platform=${BUILDPLATFORM:-foobar} alpine AS build

RUN apk add --no-cache \
    nodejs \
    npm {{ options.ship_packages | join(" ") }} {{ options.devel_packages | join(" ") }} && apk cache clean

WORKDIR /home/app

COPY ./ ./
RUN npm i

FROM --platform=${BUILDPLATFORM:-foobar} alpine AS ship
RUN apk add --no-cache \
    nodejs \
    curl {{ options.ship_packages | join " " }}
RUN addgroup -S app && adduser app -S -G app

WORKDIR /home/app
USER app

COPY --from=build /home/app/  .

CMD ["node", "funko.js"]
HEALTHCHECK {{ options.healthcheck_options }}  CMD {{ options.healthcheck_command }}
