FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine AS build
RUN apk add --no-cache \
    crystal \
    shards \
    openssl-dev \
    zlib-dev {{ options.ship_packages | join(" ") }} {{ options.devel_packages | join(" ") }}

WORKDIR /home/app

COPY ./ ./
RUN shards install
RUN shards build {{ options.shard_build_options }}
RUN strip bin/*
CMD ["./bin/funko"]

FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine AS ship
RUN apk add --no-cache \
    pcre2 \
    libgcc \
    gc \
    libevent \
    curl {{ options.ship_packages | join " " }}

RUN addgroup -S app && adduser app -S -G app

WORKDIR /home/app
COPY --from=build /home/app/public/ /home/app/public/
COPY --from=build /home/app/bin/funko /home/app/
USER app

CMD ["./funko"]
HEALTHCHECK {{ options.healthcheck_options }}  CMD {{ options.healthcheck_command }}
