ARG BUILDPLATFORM
FROM --platform=${BUILDPLATFORM:-amd64} alpine AS build

RUN apk add --no-cache \
    python3 \
    build-base \
    python3-dev {{ options.ship_packages | join(" ") }} {{ options.devel_packages | join(" ") }}

WORKDIR /home/app

COPY . .
RUN chmod 755 run.sh
RUN python3 -m venv venv
RUN venv/bin/pip install -r requirements.txt

FROM --platform=${BUILDPLATFORM:-amd64} alpine AS ship
RUN apk add --no-cache \
    python3 \
    uwsgi \
    uwsgi-python3 \
    uwsgi-http \
    curl {{ options.ship_packages | join " " }}

RUN addgroup -S app && adduser app -S -G app

WORKDIR /home/app
{% for item in options.copy_from_build %}
COPY --from=build /home/app/{{item}}
{% endfor %}
USER app

CMD ["./run.sh"]
HEALTHCHECK {{ options.healthcheck_options }}  CMD {{ options.healthcheck_command }}
