ARG BUILDPLATFORM
FROM --platform=${BUILDPLATFORM:-foobar} alpine AS build
FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine as build

RUN apk add --no-cache \
    python3 \
    gcc \
    musl-dev \
    linux-headers \
    python3-dev {{ options.ship_packages | join(" ") }} {{ options.devel_packages | join(" ") }}

WORKDIR /home/app

COPY requirements.txt *.py ./
RUN python3 -m venv venv
RUN venv/bin/pip install uwsgi
RUN venv/bin/pip install -r requirements.txt

FROM --platform=${BUILDPLATFORM:-foobar} alpine AS ship
RUN apk add --no-cache \
    python3 \
    uwsgi \
    curl {{ options.ship_packages | join " " }}

RUN addgroup -S app && adduser app -S -G app

WORKDIR /home/app
USER app

COPY --from=build /home/app/  .

CMD ["venv/bin/uwsgi", "--http", "0.0.0.0:3000", "--master", "-p", "1", "-w", "funko:app"]
HEALTHCHECK {{ options.healthcheck_options }}  CMD {{ options.healthcheck_command }}
